### PR TITLE
Port to ROS2

### PR DESCRIPTION
**Pull request by vatanaksoytezer**

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
Ignore the other PR please, accidentally push to ros2 branch of this repo and reverted.

**Comment by lauralindzey** [comment]
Awesome -- thank you so much for taking this on @vatanaksoytezer! 

I've taken a quick look, and it seems fine to me, but I also haven't used ROS2 yet so I'm not the right person to review this =)
My only comment is that maybe I should clean up the package.xml files in the main branch so the diffs are as minimal as possible, but that can come later.

@CaptKrasno -- I'll let you do the honors of merging when you're happy =) I don't have strong feelings about it, but if I recall correctly, @vatanaksoytezer prefers if PRs are squashed and merged.

**Review by lauralindzey — APPROVED** [review]

**Comment by CaptKrasno** [comment]
Took a quick look.   It seems fine at first glance.   I will clone and test it quickly this afternoon then merge the pull request.

@vatanaksoytezer, thanks for your quick response!

**Comment by CaptKrasno** [comment]
Tested.   Seems to work fine!.   

Merging

**Review by CaptKrasno — APPROVED** [review]

**Pull request merged**
