### PR TITLE
Added environmental_msgs package and TurbidityNTU message.

### PR DESCRIPTION
**Pull request by amarburg**
Also created brief README for environmental_msgs package.

### CODE REVIEW

**Comment by lauralindzey** [comment]
Thanks for the PR @amarburg! I'll plan to merge this no sooner than next Wednesday, to give the other maintainers (@bsb808, @CaptKrasno) time to comment if they wish to iterate before moving ahead.

Aaron and I discussed this message a bit, so I'll go ahead and add more context:

There are a number of different measures of Turbidity, and they aren't trivial to convert between since they're actually measuring different physical properties of the water. So, it's not as simple as mandating "thou shalt convert to SI units" and using a single message.

We see two approaches to this:
1) Separate message for each measurement, as in this PR. (e.g. TurbidityNTU.msg, TurbidityJTU.msg, ...)
2) A single Turbidity.msg, with an enum indicating what units and measurement technology is being used.

I haven't found any precedent for what other groups are using for Turbidity messages. WHOI's optical backscatter data doesn't use a dedicated message -- instead, they have a generic message for all of the analog-to-digital sensors on the vehicle, and any interpretation of the value happens after the dive. So, I can't use my typical strategy of starting with what they defined ;-)

**Comment by amarburg** [comment]
I also didn't expect to be the flag bearer for the environmental_msgs package.  So let me know if we want to make that a separate discussion, etc.

**Comment by amarburg** [comment]
Ping on this pull request.    I believe we came to a conclusion on the "units baked into message definition" versus "units stored as metadata in message" debate, but I forget where we settled.

**Comment by lauralindzey** [comment]
Hi @amarburg -- I just went back and checked my notes to confirm that we had indeed agreed that having separate message definitions per measurement type. 

I think environmental_msgs makes total sense as a subcategory, so thanks for creating it!

**Pull request merged**
